# Generated by Django 3.2 on 2023-04-14 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hate_users',
            field=models.ManyToManyField(related_name='hate_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
